/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":plugins-test-shared"))
}

description = "Foomp-Plugins-Test (Implementation 2)"

java {
    withJavadocJar()
}
